# @package _global_.local_encoder

_target_: src.local_encoder.LocalEncoder
vocab_size: ${vocab_size}
pad_token_id: ${pad_token_id}
embed_dim: ${experiment.embed_dim}
num_heads: ${experiment.num_heads}
ffn_dim: ${experiment.ffn_dim}
num_layers: ${experiment.local_encoder_num_layers}
local_window_size: ${experiment.local_window_size}
merge_group_dim: 64
max_seq_len: ${experiment.max_seq_len}
compression_ratio_mean: 0.5
compression_ratio_min: 0.4
compression_ratio_max: 0.6
