# @package _global_.local_decoder

_target_: src.local_decoder.LocalDecoder
vocab_size: ${vocab_size}
embed_dim: ${experiment.embed_dim}
num_heads: ${experiment.num_heads}
ffn_dim: ${experiment.ffn_dim}
num_layers: ${experiment.local_decoder_num_layers}
local_window_size: ${experiment.local_window_size}
max_seq_len: ${experiment.max_seq_len}
