# @package _global_.dataset

_target_: dataset.synthetic_vocab.SyntheticVocabDNADataset
num_sequences: 100000
dataset_len: 10000
min_seq_len: 24
max_seq_len: ${experiment.max_seq_len}
vocab_size: 100
min_k: 2
max_k: 8
seed: 42
