# @package _global_.latent_decoder

_target_: latent_decoder.default.LatentDecoder
embed_dim: ${experiment.embed_dim}
num_heads: ${experiment.num_heads}
ffn_dim: ${experiment.ffn_dim}
num_layers: ${experiment.latent_decoder_num_layers}
max_seq_len: ${experiment.max_seq_len}
